### ISSUE TITLE
Rsa claves

### ISSUE THREAD

**Issue by marcuxyz** [juusechec/jwt-beego#1]
¿Cómo giro las claves RSA?

Gracias

**Comment by juusechec** [comment]
¿A qué te refieres con girar?

**Comment by marcuxyz** [comment]
girar = generate
sorry my spanish.

He resuelto el problema mirando este archivo:

Https://github.com/juusechec/jwt-beego/blob/master/generar_key.log

¡Gracias!

En el archivo README.MD no entiendo muy bien, cómo bloquear una dirección URL?
  Cuando utilizo el método de preparación () se bloquea todo con el mensaje:

"Permission Deny"

**Comment by juusechec** [comment]
Ok, no problem. You can change 2048 key length by another bigger number to increase security key.
The second question... *Prepare* is the function that executed before other controller actions. If variable ***tokenString*** is valid (you can print in console via "fmt" or "log" package) the controller continue normally the next functions. The variable ***valido*** must be *true* to controller can executed the rest of functions.
